- apis/core-api/src/api/routes/v1/users/ControllerAdapter.ts
- apis/core-api/src/api/routes/v1/users/index.ts
- apis/core-api/src/core/controllers/UserController/UserController.ts
- apis/core-api/src/core/controllers/UserController/types.ts
- apis/core-api/src/core/data/models/UserSession.ts
- apis/core-api/src/core/services/AuthService.ts
Delete user auth token functionality, but keep data in the database with deleted flag.
> Delete user auth token functionality 

- apis/core-api/src/core/data/lcp/resources.ts
- apis/core-api/src/core/data/models/City.ts
- apis/core-api/src/core/data/models/FanClub.ts
- apis/core-api/src/core/data/models/FanClubMember.ts
- packages/utils/src/enums/FanClubMemberRoleEnum.ts
- packages/utils/src/enums/FanClubMemberStatusEnum.ts
- packages/utils/src/enums/FanClubPrivacyEnum.ts
- packages/utils/src/enums/index.ts
- sdks/core-api-sdk/src/sdks/UserSDK/types.d.ts
1) Database models was created with their relations.
2) Enums for Fan club model created.
> FanClub and FanClubMember models created

- apis/core-api/src/api/middlewares/check-user-auth/index.ts
- apis/core-api/src/api/routes/v1/fanClubs/ControllerAdapter.ts
- apis/core-api/src/api/routes/v1/fanClubs/index.ts
- apis/core-api/src/api/routes/v1/index.ts
- apis/core-api/src/core/controllers/FanClubController/FanClubController.ts
- apis/core-api/src/core/controllers/FanClubController/index.ts
- apis/core-api/src/core/controllers/FanClubController/types.ts
- apis/core-api/src/core/controllers/UserController/UserController.ts
- apis/core-api/src/core/services/AuthService.ts
- apis/core-api/src/core/services/FanClubService.ts
- apis/core-api/src/core/services/index.ts
- apis/core-api/src/modules/modifier/responseHandler.ts
1) FanClub create functionality.
2) FanClub update functionality.
3) AuthToken middleware regenerate token in error responses too.
> FanClub create and edit functionality.

- apis/core-api/.eslintrc
- apis/core-api/src/api/middlewares/check-fan-club-existence/index.ts
- apis/core-api/src/api/middlewares/check-fan-club-role/index.ts
- apis/core-api/src/api/middlewares/check-fan-club-status/index.ts
- apis/core-api/src/api/routes/v1/fanClubs/admin/ControllerAdapter.ts
- apis/core-api/src/api/routes/v1/fanClubs/admin/index.ts
- apis/core-api/src/api/routes/v1/fanClubs/fanClubs/ControllerAdapter.ts
- apis/core-api/src/api/routes/v1/fanClubs/fanClubs/index.ts
- apis/core-api/src/api/routes/v1/fanClubs/index.ts
- apis/core-api/src/core/controllers/FanClubController/FanClubController.ts
- apis/core-api/src/core/controllers/FanClubMembershipController/FanClubMembershipController.ts
- apis/core-api/src/core/controllers/FanClubMembershipController/index.ts
- apis/core-api/src/core/controllers/FanClubMembershipController/types.ts
- apis/core-api/src/core/data/config/config.js
- apis/core-api/src/core/services/BaseService.ts
- apis/core-api/src/core/services/FanClubMemberService.ts
- apis/core-api/src/core/services/FanClubService.ts
- apis/core-api/src/core/services/UserService.ts
- apis/core-api/src/core/services/index.ts
Fan Club Admin `Add/Remove` Actions:
1) Add a single member
2) Add multiple members
3) Remove single member
4) Remove multiple members
> Fan club membership add/remove by admin or owner

- apis/core-api/src/api/routes/v1/fanClubs/admin/ControllerAdapter.ts
- apis/core-api/src/api/routes/v1/fanClubs/admin/index.ts
- apis/core-api/src/core/controllers/FanClubMembershipController/FanClubMembershipController.ts
- apis/core-api/src/core/services/FanClubMemberService.ts
Fan Club Admin `Update/Get/ Actions:
1) Get all members of the fan club
2) Get membership by id
3) Update single membership
4) Update multiple memberships
> Fan club membership update/get by admin or owner

- apis/core-api/src/api/routes/v1/fanClubs/index.ts
- apis/core-api/src/api/routes/v1/fanClubs/member/ControllerAdapter.ts
- apis/core-api/src/api/routes/v1/fanClubs/member/index.ts
- apis/core-api/src/core/controllers/FanClubMembershipController/FanClubMembershipController.ts
Fan Club Member `Join/Leave/Get` Actions:
1) Request to join one fan club
2) Request to join multiple fan clubs
3) Get my fan clubs
4) Leave fan club
> Fan club membership request/leave/get by member

- apis/core-api/src/api/routes/v1/fanClubs/admin/ControllerAdapter.ts
- apis/core-api/src/api/routes/v1/fanClubs/admin/index.ts
- apis/core-api/src/api/routes/v1/fanClubs/member/ControllerAdapter.ts
- apis/core-api/src/api/routes/v1/fanClubs/member/index.ts
- apis/core-api/src/core/controllers/FanClubMembershipController/FanClubMembershipController.ts
Fan Club Join `Accept Invitation` / `Reject Invitation` Actions by Member and `Accept Request` / `Reject Request` Actions by Admin:
1) Member accept the invitation
2) Member reject the invitation
3) Admin accept join request
4) Admin reject join request
> Fan club membership accept/reject request

- apis/core-api/src/api/routes/v1/fanClubs/fanClubs/ControllerAdapter.ts
- apis/core-api/src/core/data/models/FanClub.ts
- apis/core-api/src/core/services/FanClubMemberService.ts
- apis/core-api/src/core/services/FanClubService.ts
fan club members count field and calculation functionality added
> fan club members count field added

- apis/core-api/src/core/services/FanClubMemberService.ts
- apis/core-api/src/core/services/FanClubService.ts
Fan club members counting logic update, now it will be updated when:
1) Owner or admin accepted user join request
2) User accepted fan club owner/admin invitation
3) User leaves fan club
4) Owner/admin remove user from fan club
> Fan club members counting logic

- clients/app/src/core/stores/footballClubs/index.ts
- clients/app/src/core/stores/generateCRUD/index.ts
- clients/app/src/core/stores/generateCRUD/types.ts
- clients/app/src/core/stores/nationalTeams/index.ts
Generate state and methods to work with the state using provided keys with strict typescript checking.
> Generate CRUD state by provided keys

- .gitignore
- clients/app/babel.config.js
- scripts/.helpers.sh
- scripts/init-app.sh
PR includes:
1) React Native import aliases fixed.
2) Initiator script bug fixes (OS depended).
3) Some script improvements
4) Keep initiator script output into a log file.
> React Native import aliases fixed & bash script bug fixed & improvements

- sdks/core-api-sdk/.env.example
- sdks/core-api-sdk/package.json
- sdks/core-api-sdk/scripts/postbuild.js
- sdks/core-api-sdk/src/configs.ts
- sdks/core-api-sdk/src/sdks/CoreApiBaseSDK.ts
API host comes from .env configuration file.
> SDK using .env file configuration.

- apis/core-api/src/core/controllers/LeagueController/LeagueController.ts
- apis/core-api/src/core/controllers/TeamController/TeamController.ts
- apis/core-api/src/core/controllers/VenueController/VenueController.ts
- apis/core-api/src/core/data/inject-scripts/injectCities.ts
- apis/core-api/src/core/data/models/City.ts
- apis/core-api/src/core/data/models/FanClub.ts
- apis/core-api/src/core/data/models/FanClubMember.ts
- apis/core-api/src/core/data/models/FavoriteTeam.ts
- apis/core-api/src/core/data/models/League.ts
- apis/core-api/src/core/data/models/Match.ts
- apis/core-api/src/core/data/models/Team.ts
- apis/core-api/src/core/data/models/Venue.ts
- apis/core-api/src/core/services/CityService.ts
- apis/core-api/src/core/services/CountryService.ts
- apis/core-api/src/core/services/LeagueService.ts
- apis/core-api/src/core/services/MatchService.ts
- apis/core-api/src/core/services/TeamService.ts
- apis/core-api/src/core/services/VenueService.ts
This PR includes injection script fixes and model ID data types compatibility updates.
> Injection issue fixes and models data-type updated.

- apis/core-api/src/core/services/CityService.ts
- apis/core-api/src/core/services/FanClubMemberService.ts
- apis/core-api/src/core/services/FanClubService.ts
- apis/core-api/src/core/services/FavoriteTeamService.ts
- apis/core-api/src/core/services/LeagueService.ts
- apis/core-api/src/core/services/TeamService.ts
- apis/core-api/src/core/services/VenueService.ts
- scripts/.helpers.sh
In this PR we have added nested relations of models.
> nested relations added

- apis/core-api/src/core/services/FanClubService.ts
- clients/app/src/i18n/locales/en.ts
- clients/app/src/stores/fanClubs.ts
- clients/app/src/stores/matches.ts
- clients/app/src/stores/teams.ts
- clients/app/src/views/components/compositions/FanClubInfo/FanClubInfo.tsx
- clients/app/src/views/components/compositions/MatchInfo/MatchInfo.tsx
- clients/app/src/views/components/compositions/SearchItem/components/SearchItemComponent.tsx
- clients/app/src/views/components/compositions/SearchItem/containers/SearchItemContainer.tsx
- clients/app/src/views/components/compositions/SearchItem/types.ts
- clients/app/src/views/components/compositions/TeamCard/TeamCard.tsx
- clients/app/src/views/components/compositions/TeamCard/types.ts
- clients/app/src/views/components/compositions/TeamInfo/TeamInfo.tsx
- clients/app/src/views/components/compositions/TeamInfo/types.ts
- clients/app/src/views/containers/TeamsHorizontal/TeamsContainer.tsx
- clients/app/src/views/navigation/screens/searchTabScreens.ts
- clients/app/src/views/navigation/types.ts
- clients/app/src/views/screens/Matches/containers/MatchesContainer.tsx
- clients/app/src/views/screens/Matches/types.ts
- clients/app/src/views/screens/Search/components/SearchTabNavigation.tsx
- clients/app/src/views/screens/SearchListModal/components/ListModalTabNavigation.tsx
- clients/app/src/views/screens/Team/Team.tsx
- clients/app/src/views/screens/Team/components/TeamComponent.tsx
- clients/app/src/views/screens/Team/components/TeamTabNavigation.tsx
- clients/app/src/views/screens/Team/containers/TeamContainer.tsx
- clients/app/src/views/screens/Team/types.ts
Connect Teams data to back-end,
Filter matches for team
> [feat] Connect teams data to back-end

- clients/app/src/styles/styles.ts
- clients/app/src/themes/theming/options/fontConfigs.ts
- clients/app/src/themes/theming/options/fontSizes.ts
- clients/app/src/themes/theming/theme.ts
- clients/app/src/views/components/base/UltrasText/UltrasText.tsx
- clients/app/src/views/components/compositions/EventCard/styles.ts
- clients/app/src/views/components/compositions/EventInfo/styles.ts
- clients/app/src/views/components/compositions/FanClubCard/styles.ts
- clients/app/src/views/components/compositions/FanClubInfo/styles.ts
- clients/app/src/views/components/compositions/FanClubsHorizontal/styles.ts
- clients/app/src/views/components/compositions/FourDigitsInput/styles.ts
- clients/app/src/views/components/compositions/PostCard/styles.ts
- clients/app/src/views/components/compositions/PostInfo/styles.ts
- clients/app/src/views/components/compositions/ProfileCard/styles.ts
- clients/app/src/views/components/compositions/ProfileInfo/styles.ts
- clients/app/src/views/components/compositions/TeamCard/styles.ts
- clients/app/src/views/components/compositions/TeamInfo/styles.ts
- clients/app/src/views/components/compositions/TeamsHorizontal/styles.ts
- clients/app/src/views/navigation/RootNavigation.tsx
- clients/app/src/views/navigation/screens/rootScreens.tsx
- clients/app/src/views/screens/FanClubAbout/styles.ts
- clients/app/src/views/screens/Home/styles.ts
- clients/app/src/views/screens/SearchListModal/components/styles.ts
- clients/app/src/views/screens/SearchListModal/styles.ts
- clients/app/src/views/screens/Splash/styles.ts
- lerna.json
- scripts/.helpers.sh
- scripts/init-app.sh
Theming font configuration setup.
> theming basic setup with font configs

- clients/web-tests/src/lib-tests/sdk-comments.ts
- clients/web-tests/src/tests.ts
- sdks/core-api-sdk/src/sdks/CommentableInterface.ts
- sdks/core-api-sdk/src/sdks/EventSDK/index.ts
- sdks/core-api-sdk/src/sdks/LikeableInterface.ts
- sdks/core-api-sdk/src/sdks/MatchSDK/index.ts
- sdks/core-api-sdk/src/sdks/RoomSDK/index.ts
Comment functionality added to  SDKs
> Comment functionality added to  SDKs

- apis/core-api/src/api/routes/v1/events/comments/ControllerAdapter.ts
- apis/core-api/src/api/routes/v1/events/comments/index.ts
- apis/core-api/src/api/routes/v1/events/index.ts
- apis/core-api/src/api/routes/v1/matches/comments/ControllerAdapter.ts
- apis/core-api/src/api/routes/v1/matches/comments/index.ts
- apis/core-api/src/api/routes/v1/matches/index.ts
- apis/core-api/src/api/routes/v1/rooms/comments/ControllerAdapter.ts
- apis/core-api/src/api/routes/v1/rooms/comments/index.ts
- apis/core-api/src/api/routes/v1/rooms/index.ts
- apis/core-api/src/core/controllers/EventCommentController/EventCommentController.ts
- apis/core-api/src/core/controllers/EventCommentController/index.ts
- apis/core-api/src/core/controllers/EventCommentController/types.ts
- apis/core-api/src/core/controllers/MatchCommentController/MatchCommentController.ts
- apis/core-api/src/core/controllers/MatchCommentController/index.ts
- apis/core-api/src/core/controllers/MatchCommentController/types.ts
- apis/core-api/src/core/controllers/RoomCommentController/RoomCommentController.ts
- apis/core-api/src/core/controllers/RoomCommentController/index.ts
- apis/core-api/src/core/controllers/RoomCommentController/types.ts
- apis/core-api/src/core/data/models/Comment.ts
- apis/core-api/src/core/data/models/Match.ts
- apis/core-api/src/core/data/models/Post.ts
- apis/core-api/src/core/data/models/User.ts
- apis/core-api/src/core/services/CommentService.ts
- apis/core-api/src/core/services/LikeService.ts
- apis/core-api/src/core/services/index.ts
- view-models/core-api/src/index.ts
- view-models/core-api/src/view-models/comment.ts
Comment Service and API for Events
> Comment Service + API for Events

- apis/core-api/src/core/services/PostMemberService.ts
- apis/core-api/src/core/services/PostService.ts
- clients/app/src/stores/eventMembers/eventMembers.ts
- clients/app/src/stores/eventMembers/index.ts
- clients/app/src/stores/eventMembers/types.ts
- clients/app/src/views/screens/Event/components/EventComponent.tsx
- sdks/core-api-sdk/src/sdks/EventMemberSDK/types.ts
- sdks/core-api-sdk/src/sdks/RoomMemberSDK/types.ts
- view-models/core-api/src/index.ts
- view-models/core-api/src/view-models/eventMember.ts
- view-models/core-api/src/view-models/post.ts
- view-models/core-api/src/view-models/roomMember.ts
This PR includes the `join event` and `leave event` functionality on the mobile app.
> [feat] Join/Leave event

- apis/core-api/src/core/services/MatchService.ts
The matches injection script was updated and added functionality to the update existing matches.
> [fix] match injection script fixes

- apis/core-api/src/api/middlewares/check-user-auth/index.ts
- apis/core-api/src/api/middlewares/parse-auth-token/index.ts
- apis/core-api/src/core/services/AuthService.ts
- clients/app/src/stores/authentication/authentication.ts
Fixed bug that will trigger logout during parallel requests with the expired auth-token.
> [feat] auto-logout fixes 

- apis/core-api/src/core/controllers/EventController/EventController.ts
- apis/core-api/src/core/controllers/FanClubController/FanClubController.ts
- apis/core-api/src/core/controllers/FanClubController/types.ts
- clients/app/src/stores/generateCRUD/crud/add.ts
- clients/app/src/stores/generateCRUD/types/crud/add.ts
- clients/app/src/views/components/compositions/AttacheImage/AttacheImage.tsx
- clients/app/src/views/screens/CreateEvent/screens/CreateEvent/containers/CreateEventContainer.tsx
- clients/app/src/views/screens/CreateFanClub/screens/CreateFanClub/CreateFanClub.tsx
- _[API]_ Return instance with relations after creation.
- _[Front]_ Added field (API creation response).
- _[Front]_ Open screens after `Event`/`FanClub` creation.
> [feat] Open FanClub/Event screen after creation.

- clients/app/src/stores/events/scheme.ts
- clients/app/src/stores/fanClubs/fanClubs.ts
- clients/app/src/stores/fanClubs/scheme.ts
- clients/app/src/views/navigation/screens/createEventScreens.ts
- clients/app/src/views/navigation/screens/createFanClubScreens.ts
- clients/app/src/views/screens/CreateEvent/screens/CreateEvent/components/CreateEventComponent.tsx
- clients/app/src/views/screens/CreateEvent/screens/CreateEvent/containers/CreateEventContainer.tsx
- clients/app/src/views/screens/CreateEvent/screens/CreateEvent/types.d.ts
- clients/app/src/views/screens/CreateFanClub/screens/CreateFanClub/CreateFanClub.tsx
---
- Duplicate nested screen names was renamed:
- `CreateFanClub` screen renamed to `CreateFanClubForm`
- `CreateEvent` screen renamed to `CreateEventForm`
- Validations was fixed for `CreateEvent` and `CreateFanClub`.
- Create fan club multi-screen wizard logic changed, (need to fill all required fields to navigate to next screen).
> [fix] create event/fan-club validation fixes.

- clients/app/src/utils/helpers/matchTime.ts
- clients/app/src/views/components/compositions/MatchTime/MatchTime.tsx
- clients/app/src/views/components/compositions/ProfileCard/ProfileCard.tsx
- clients/app/src/views/components/compositions/ProfileCard/types.ts
- clients/app/src/views/components/compositions/SearchItem/components/SearchItemComponent.tsx
- clients/app/src/views/screens/CreateEvent/screens/SelectMatch/components/SelectMatchComponent.tsx
- clients/app/src/views/screens/CreateFanClub/screens/SelectCity/components/SelectCityComponent.tsx
- clients/app/src/views/screens/Events/components/EventsComponent.tsx
- clients/app/src/views/screens/Matches/components/MatchesComponent.tsx
- clients/app/src/views/screens/ProfileList/components/ProfileListComponent.tsx
---
1) Added spacing for `FlatList` components with no spacing from the device's borders.
2) Show `-:-` for the match's time if it has a `time-to-be-defined` status.
3) Some typo fixes.
> [fix] FlatList spacing fixes.

- clients/app/src/views/screens/CreateFanClub/screens/CreateFanClub/CreateFanClub.tsx
- clients/app/src/views/screens/CreateFanClub/screens/CreateFanClub/containers/DetailsContainer.tsx
- clients/app/src/views/screens/CreateFanClub/screens/CreateFanClub/containers/SwiperContainer.tsx
- clients/app/src/views/screens/CreateFanClub/screens/CreateFanClub/types.ts
- sdks/core-api-sdk/src/sdks/FanClubSDK/types.ts
---
- Moved the `ScrollView` component from the child to the top of `SwiperView` - to make scrolling available when input focused.
- Fixed bug - on input focus scroll around to.
- Unnecessary styles removed.
> [fix] Create fan club screen - Scroll on input focus bug fixed.

- apis/core-api/nodemon.json
- apis/core-api/src/api/routes/v1/matches/ControllerAdapter.ts
- apis/core-api/src/api/routes/v1/matches/index.ts
- apis/core-api/src/core/controllers/MatchController/MatchController.ts
- apis/core-api/src/core/data/inject-scripts/injectMatches.ts
- apis/core-api/src/core/services/MatchService.ts
---
- `nodemon` configuration updated to handle `UnhandledPromiseRejectionWarning`.
- Added new matches injection functionality using seasons.
---
> [feat] Inject matches by season.

- apis/core-api/src/api/index.ts
- apis/core-api/src/module-alias.js
- apis/core-api/src/modules/initializators/App.ts
- apis/core-api/src/modules/initializators/Database.ts
Use the same port for production mode, and forward requests using `nginx proxy pass`.
> [fix] Use same port for production mode.

- apis/core-api/.gitignore
- apis/core-api/ecosystem.config.js
- apis/core-api/package.json
- apis/core-api/scripts/build.sh
- apis/core-api/tsconfig.json
> Fix/core api/build pm2

- apis/core-api/src/core/services/CityService.ts
- apis/core-api/src/core/services/CountryService.ts
- apis/core-api/src/core/services/EventService.ts
- apis/core-api/src/core/services/FanClubMemberService.ts
- apis/core-api/src/core/services/FanClubService.ts
- apis/core-api/src/core/services/FavoriteTeamService.ts
- apis/core-api/src/core/services/LeagueService.ts
- apis/core-api/src/core/services/PostMemberService.ts
- apis/core-api/src/core/services/RoomService.ts
- apis/core-api/src/core/services/TeamService.ts
- apis/core-api/src/core/services/VenueService.ts
`iCatch` replaced with `iLike`.
> [fix] `iCatch` replaced with `iLike`.

- .github/workflows/deploy-development.yaml
Loading Linux OS profile file before staring deployment.
> [fix] load linux profile before deployment

- sdks/core-api-sdk/src/sdks/UserSDK/index.ts
- sdks/core-api-sdk/src/sdks/UserSDK/types.ts
Added functionality into `UserSDK` to update the user's profile.
> [feat] Added SDK functionality to update user's profile.

- apis/core-api/src/core/data/models/User.ts
Added field for user profile privacy.
> [fix] added user privacy field to database

- clients/app/ios/Podfile.lock
- clients/app/src/stores/eventCatches/eventCatches.ts
- clients/app/src/stores/eventCatches/index.ts
- clients/app/src/stores/eventCatches/types.ts
- clients/app/src/stores/matchCatches/index.ts
- clients/app/src/stores/matchCatches/matchCatches.ts
- clients/app/src/stores/matchCatches/types.ts
- clients/app/src/stores/roomCatches/index.ts
- clients/app/src/stores/roomCatches/roomCatches.ts
- clients/app/src/stores/roomCatches/types.ts
- clients/app/src/stores/sdkBuilder/makeSdkInstance.ts
- clients/app/src/stores/sdkBuilder/sdkBuilder.ts
- clients/app/src/views/components/base/Catch/Catch.tsx
- clients/app/src/views/components/base/Catch/type.ts
- clients/app/src/views/components/compositions/EventCard/EventCard.tsx
- clients/app/src/views/screens/Event/components/EventComponent.tsx
- clients/app/src/views/screens/Match/Match.tsx
- clients/app/src/views/screens/Match/components/MatchCatchComponent.tsx
- clients/app/src/views/screens/Match/types.ts
- clients/app/src/views/screens/Room/components/RoomComponent.tsx
- clients/web-tests/src/lib-tests/sdk-catches.ts
- packages/services/NetworkService/index.ts
- sdks/core-api-sdk/src/sdks/EventSDK/index.ts
- sdks/core-api-sdk/src/sdks/ICatchable.ts
- sdks/core-api-sdk/src/sdks/MatchSDK/index.ts
- sdks/core-api-sdk/src/sdks/RoomSDK/index.ts
- view-models/core-api/src/view-models/match.ts
- view-models/core-api/src/view-models/post.ts
---
- Added Like functionality for Matches, Events, and Rooms.
- Remove the last slash from the URL before sending the request
- That can cause nginx issue which cuts query string.
> [feat] added Catch functionality for Matches, Events and Rooms

- clients/app/src/i18n/locales/en.ts
- clients/app/src/stores/eventCatches/eventCatches.ts
- clients/app/src/stores/eventCatches/types.ts
- clients/app/src/stores/eventMembers/types.ts
- clients/app/src/stores/generateCRUD/types/common.ts
- clients/app/src/stores/matchCatches/matchCatches.ts
- clients/app/src/stores/matchCatches/types.ts
- clients/app/src/stores/roomCatches/roomCatches.ts
- clients/app/src/stores/roomCatches/types.ts
- clients/app/src/styles/styles.ts
- clients/app/src/utils/helpers/dummy.ts
- clients/app/src/views/components/base/Catch/Catch.tsx
- clients/app/src/views/components/base/Catch/styles.ts
- clients/app/src/views/components/base/Catch/type.ts
- clients/app/src/views/components/compositions/ProfileCard/ProfileCard.tsx
- clients/app/src/views/components/compositions/ProfileCard/types.ts
- clients/app/src/views/screens/Event/components/EventComponent.tsx
- clients/app/src/views/screens/FanClub/components/FanClubComponent.tsx
- clients/app/src/views/screens/Match/components/MatchCatchComponent.tsx
- clients/app/src/views/screens/ProfileList/ProfileList.tsx
- clients/app/src/views/screens/ProfileList/components/ProfileListComponent.tsx
- clients/app/src/views/screens/ProfileList/containers/ProfileListContainer.tsx
- clients/app/src/views/screens/ProfileList/types.ts
- clients/app/src/views/screens/Room/components/RoomComponent.tsx
- sdks/core-api-sdk/src/sdks/EventSDK/index.ts
- sdks/core-api-sdk/src/sdks/ICatchable.ts
- sdks/core-api-sdk/src/sdks/MatchSDK/index.ts
- sdks/core-api-sdk/src/sdks/RoomSDK/index.ts
- sdks/core-api-sdk/src/sdks/types.ts
---
- Added filtering support for `Catches` in `EventSDK`, `RoomSDK`, and `MatchSDK`.
- Added loading method for `Catches` in `EventStore`, `RoomStore`, and `MatchStore`.
- Finalized the `ProfileList` component.
> [feat] users list screen

- apis/core-api/src/core/controllers/EventCatchController/EventCatchController.ts
- apis/core-api/src/core/controllers/MatchCatchController/MatchCatchController.ts
- apis/core-api/src/core/controllers/RoomCatchController/RoomCatchController.ts
- apis/core-api/src/core/services/CatchService.ts
Added total field on catch-list responses.
> [fix] added total field on catch-list responses

- clients/app/src/views/components/compositions/FourDigits/components/FourDigitsInputs.tsx
- clients/app/src/views/components/compositions/FourDigits/types.ts
- clients/app/src/views/screens/JoinUs/components/JoinUsComponent.tsx
---
- Show the number in the four-digit component when the API call is started.
- Scroll to the end of the `Login`/`Register` screen after the step change.
> [fix] Some UI bugs fixed in mobile app.

- apis/core-api/src/core/controllers/UserController/UserController.ts
- apis/core-api/src/core/controllers/UserController/types.ts
- clients/app/src/stores/editProfile/editProfile.ts
- clients/app/src/stores/editProfile/types.ts
- clients/app/src/views/components/compositions/FourDigits/components/FourDigitsMessage.tsx
- clients/app/src/views/screens/EditProfile/screens/EditProfile/EditProfile.tsx
- clients/app/src/views/screens/EditProfile/screens/EditProfile/EditProfileLoader.tsx
- clients/app/src/views/screens/EditProfile/screens/UpdateField/containers/UpdateFieldContainer.tsx
- clients/app/src/views/screens/Profile/Profile.tsx
Update the user profile on the mobile app.
> [feat] Update user profile

- packages/services/NetworkService/index.ts
- packages/services/__tests__/services.test.js
Remove the last slash from the API call URL to make a correct call to the server.
> [fix] Remove last slash from pathname of API call url.

- apis/core-api/src/core/data/models/Match.ts
- apis/core-api/src/core/data/models/Post.ts
- apis/core-api/src/core/services/CatchService.ts
- apis/core-api/src/core/services/CommentService.ts
- apis/core-api/src/core/services/MatchService.ts
- apis/core-api/src/core/services/PostService.ts
---
- Added `commentsCount` and `catchesCount` fields on `Match` model.
- Added logic to increment/decrement count of comments/catches on `Match` and `Post`.
> [feat] update catches/comments count.

- apis/core-api/src/api/index.ts
- apis/core-api/src/api/routes/v1/matches/ControllerAdapter.ts
- apis/core-api/src/api/routes/v1/matches/index.ts
- apis/core-api/src/config/index.ts
- apis/core-api/src/core/controllers/MatchCatchController/MatchCatchController.ts
- apis/core-api/src/core/controllers/MatchCatchController/types.ts
- apis/core-api/src/core/controllers/MatchCommentController/MatchCommentController.ts
- apis/core-api/src/core/controllers/MatchController/MatchController.ts
- apis/core-api/src/core/controllers/MatchController/types.ts
- apis/core-api/src/core/data/lcp/resources.ts
- apis/core-api/src/core/data/migrations/00000000000001-create-catches.ts
- apis/core-api/src/core/data/models/Catch.ts
- apis/core-api/src/core/data/models/Match.ts
- apis/core-api/src/core/data/models/Post.ts
- apis/core-api/src/core/data/models/User.ts
- apis/core-api/src/core/services/BaseService.ts
- apis/core-api/src/core/services/CatchService.ts
- apis/core-api/src/core/services/FanClubService.ts
- apis/core-api/src/core/services/MatchService.ts
- apis/core-api/src/core/services/PostService.ts
---
- Add caught __(liked)__ attribute on `event` / `room` / `match` if user is logged in.
- Sequelize warning fixes.
> [feat] add caught attribute on event/room/match if user is logged-in.

- apis/core-api/src/core/services/MatchService.ts
- apis/core-api/src/core/services/PostService.ts
- clients/app/src/stores/events/scheme.ts
- clients/app/src/views/components/base/ChooseAndUploadPhoto/ChooseAndUploadPhoto.tsx
- clients/app/src/views/components/base/ChooseAndUploadPhoto/index.ts
- clients/app/src/views/components/base/ChooseAndUploadPhoto/types.ts
- clients/app/src/views/components/compositions/AttachImage/AttachImage.tsx
- clients/app/src/views/components/compositions/AttachImage/components/ImagePreview.tsx
- clients/app/src/views/components/compositions/AttachImage/types.ts
- clients/app/src/views/components/compositions/MatchCard/MatchCard.tsx
- clients/app/src/views/screens/CreateEvent/screens/CreateEvent/components/ChoosePhotoComponent.tsx
- clients/app/src/views/screens/CreateEvent/screens/CreateEvent/components/CreateEventComponent.tsx
- clients/app/src/views/screens/CreateEvent/screens/CreateEvent/types.ts
- clients/app/src/views/screens/CreateFanClub/screens/CreateFanClub/types.ts
- sdks/core-api-sdk/src/sdks/EventSDK/types.ts
---
- Fixed issue on event creation (on API).
- Upload image component moved to global components directory.
- Upload image for the event.
> [feat] Upload image on event create

- apis/core-api/src/core/services/EventService.ts
- apis/core-api/src/core/services/MatchService.ts
- apis/core-api/src/core/services/PostService.ts
- apis/core-api/src/core/services/UserAgentService.ts
- clients/app/src/i18n/locales/en.ts
- clients/app/src/stores/editProfile/types.ts
- clients/app/src/stores/events/scheme.ts
- clients/app/src/themes/theming/components/Text.ts
- clients/app/src/views/screens/EditProfile/screens/UpdateField/containers/UpdateFieldContainer.tsx
- clients/app/src/views/screens/EditProfile/screens/UpdateField/types.ts
---
- Event creation validation (description field is not required)
- Load the `caught` field for `post.match`
- Resend confirmation code (on edit profile screen)
- Show `email` or `phone` already taken messages (on edit profile screen)
> [fix] Fixed some common known bugs

- apis/core-api/src/api/routes/v1/users/ControllerAdapter.ts
- apis/core-api/src/core/controllers/UserController/UserController.ts
- apis/core-api/src/core/controllers/UserController/types.ts
- apis/core-api/src/core/services/UserService.ts
- clients/app/src/stores/editProfile/editProfile.ts
- clients/app/src/stores/editProfile/types.ts
- clients/app/src/views/components/base/ChooseAndUploadPhoto/ChooseAndUploadPhoto.tsx
- clients/app/src/views/components/compositions/AttachImage/AttachImage.tsx
- clients/app/src/views/components/compositions/AttachImage/components/ImagePreview.tsx
- clients/app/src/views/components/compositions/AttachImage/components/PressableArea.tsx
- clients/app/src/views/components/compositions/AttachImage/components/TapToAdd.tsx
- clients/app/src/views/components/compositions/AttachImage/types.ts
- clients/app/src/views/screens/EditProfile/screens/EditProfile/components/EditAvatarComponent.tsx
- clients/app/src/views/screens/EditProfile/screens/EditProfile/components/types.ts
- clients/app/src/views/screens/EditProfile/screens/EditProfile/containers/PersonalInfoContainer.tsx
- sdks/core-api-sdk/src/sdks/UserSDK/types.ts
---
- Upload the user's profile picture.
- Choose an image on the previous image preview press.
> [feat] upload profile picture

- .aws/s3-image-resizer/lambda/source/configs.ts
- .aws/s3-image-resizer/lambda/source/lib/process.ts
- apis/core-api/src/core/services/BaseService.ts
- apis/core-api/src/core/services/aws/S3Service.ts
- clients/app/ios/ultras.xcodeproj/project.pbxproj
- clients/app/src/themes/theming/components/Avatar.ts
- clients/app/src/utils/helpers/image.ts
- clients/app/src/views/components/compositions/EventCard/EventCard.tsx
- clients/app/src/views/components/compositions/FanClubCard/FanClubCard.tsx
- clients/app/src/views/components/compositions/FanClubInfo/FanClubInfo.tsx
- clients/app/src/views/components/compositions/ProfileCard/ProfileCard.tsx
- clients/app/src/views/screens/EditProfile/screens/EditProfile/components/EditAvatarComponent.tsx
- clients/app/src/views/screens/Profile/components/ProfileInfo.tsx
- packages/utils/src/enums/AwsS3ThumbnailEnum.ts
Show uploaded image/avatar thumbnails from AWS S3.
> [feat] Show images/avatars from AWS S3.

- apis/core-api/src/api/routes/v1/fanClubs/member/ControllerAdapter.ts
- clients/app/index.js
- clients/app/src/stores/authentication/authentication.ts
- clients/app/src/stores/authentication/types.ts
- clients/app/src/views/screens/EditProfile/screens/UpdateField/containers/UpdateFieldContainer.tsx
- clients/app/src/views/screens/EditProfile/screens/UpdateField/types.ts
- clients/app/src/views/screens/Event/Event.tsx
- clients/app/src/views/screens/Event/containers/EventContainer.tsx
- clients/app/src/views/screens/FanClub/FanClub.tsx
- clients/app/src/views/screens/FanClub/containers/FanClubContainer.tsx
- clients/app/src/views/screens/Match/Match.tsx
- clients/app/src/views/screens/Match/containers/MatchContainer.tsx
- clients/app/src/views/screens/Profile/Profile.tsx
- clients/app/src/views/screens/Room/Room.tsx
- clients/app/src/views/screens/Room/containers/RoomContainer.tsx
- clients/app/src/views/screens/Team/Team.tsx
- clients/app/src/views/screens/Team/containers/TeamContainer.tsx
----
- Load data of resources in their single screens.
- Update logged user data _(on store)_ immediately after profile edit.
> [fix] load data for single resource screen

- clients/app/src/stores/events/scheme.ts
- clients/app/src/stores/fanClubs/scheme.ts
- clients/app/src/stores/generateCRUD/crud/add.ts
- clients/app/src/stores/generateCRUD/crud/update.ts
- clients/app/src/stores/generateCRUD/types/scheme.ts
- clients/app/src/stores/generateCRUD/utils/helpers.ts
- clients/app/src/views/screens/Match/containers/MatchContainer.tsx
Added functionality that allows us to access to store's state from scheme functions (`validation` and `processValue`).
> [fix] Access to store state from scheme functions in CRUD.

- clients/app/src/stores/events/scheme.ts
- clients/app/src/stores/generateCRUD/crud/add.ts
- clients/app/src/stores/generateCRUD/crud/update.ts
- clients/app/src/stores/generateCRUD/types/scheme.ts
- clients/app/src/stores/generateCRUD/utils/helpers.ts
Added possibility to set initial value as value or function in CRUD's scheme.
> [feat] initial value can be function

- clients/app/src/stores/events/scheme.ts
- clients/app/src/stores/generateCRUD/crud/add.ts
- clients/app/src/stores/generateCRUD/crud/update.ts
- clients/app/src/stores/generateCRUD/types/scheme.ts
- clients/app/src/stores/generateCRUD/utils/helpers.ts
Added logic that provides CRUD's store to scheme with freezing and via functions (to don't copy data on each validation call).
> [feat] Fayton - freeze state before passing to scheme.

- clients/app/ios/Podfile.lock
- clients/app/package.json
- clients/app/src/stores/authentication/authentication.ts
- clients/app/src/stores/editProfile/editProfile.ts
- clients/app/src/stores/generateCRUD/generateCRUD.ts
- clients/app/src/stores/registration/registration.ts
In the `zustand` state management tool some types/functions are deprecated, renamed, or changed their import location, in this PR we are using the latest version of zustand.
> [fix] Fixed some deprecated issues in zustand state management tool.
